# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=70)),
                ('jenis', models.CharField(max_length=70)),
                ('berat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gudang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokasi', models.CharField(max_length=100)),
                ('jumlah_barang', models.IntegerField()),
                ('id_pegawai', models.CharField(max_length=50)),
                ('id_barang', models.CharField(max_length=50)),
                ('tanggal_masuk', models.DateField()),
                ('tanggal_keluar', models.DateField()),
            ],
        ),
    ]
