# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitycentric', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=70)),
                ('alamat', models.CharField(max_length=100)),
                ('telepon', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pengiriman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pegawai', models.CharField(max_length=50)),
                ('id_barang', models.CharField(max_length=50)),
                ('tujuan', models.CharField(max_length=100)),
                ('id_gudang', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('biaya', models.IntegerField()),
                ('id_pegawai', models.CharField(max_length=50)),
                ('id_barang', models.CharField(max_length=50)),
            ],
        ),
    ]
